mongo:
  db:
    name: loaderdb
    url: mongodb://localhost:27017
spring:
  kafka:
    consumer:
      bootstrap: 192.168.1.64:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer